# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

resources:
   repositories:
     - repository: lambdatest
       type: github
       endpoint: Jwatts30
       name: Jwatts30/lambdatest

extends:
  template: docker-boto3/start.yml
      
